version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-hibernate
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: hibernate_db
    ports:
      - "1234:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres -c listen_addresses='*'

volumes:
  pgdata:
